### ISSUE TITLE
Overlays contain transparent / translucent pixels outside the desired area

### ISSUE THREAD

**Issue by toniosj** [thebezelproject/bezelproject-Atari5200#1]
Some overlays contain transparent / translucent pixels outside the desired area.

Carol Shaw's River Raid (USA)
Dreadnaught Factor, The (USA)
Galaxian (USA)
Joust (USA)
Pengo (USA)
Pole Position (USA)
Q-bert (USA)
Zaxxon (USA)

Here you can see the specific areas that have pixels outside the desired area.

![Carol Shaw's River Raid (USA)](https://user-images.githubusercontent.com/20826760/75109835-ac246100-5627-11ea-9d41-51fc370655ca.png)
![Dreadnaught Factor, The (USA)](https://user-images.githubusercontent.com/20826760/75109836-ad558e00-5627-11ea-8eda-cb319ac5abac.png)
![Galaxian (USA)](https://user-images.githubusercontent.com/20826760/75109837-ad558e00-5627-11ea-9b50-72e8aafe2c87.png)
![Joust (USA)](https://user-images.githubusercontent.com/20826760/75109838-adee2480-5627-11ea-8b21-d74875ad84a5.png)
![Pengo (USA)](https://user-images.githubusercontent.com/20826760/75109840-ae86bb00-5627-11ea-9bab-3227bfd2cf5e.png)
![Pole Position (USA)](https://user-images.githubusercontent.com/20826760/75109841-af1f5180-5627-11ea-97f7-71ff77d67d14.png)
![Q-bert (USA)](https://user-images.githubusercontent.com/20826760/75109842-b0507e80-5627-11ea-9458-9fe7de933c09.png)
![Zaxxon (USA)](https://user-images.githubusercontent.com/20826760/75109843-b0507e80-5627-11ea-9da9-850f81e31dde.png)

**Comment by thebezelproject** [comment]
Files have been updated.

**Comment by toniosj** [comment]
Zaxxon has not been fixed.

![Zaxxon (USA)](https://user-images.githubusercontent.com/20826760/75605147-72000700-5ae0-11ea-833b-83ab827a6202.png)

**Comment by thebezelproject** [comment]
Updated.
